name: Hi Mascot
on: push
env:
  mascot: Mona
  super_duper_var: totally_awesome

jobs:
  windows_job:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
     
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
     
     
       
          
  linux_job:
    needs: [windows_job]
    runs-on: ubuntu-latest
    steps:
    
      - run: echo '$GITHUB_OUTPUT'  # Hi Tux
      
